### ISSUE TITLE
Run node.js with jsdom in the browser grid

### ISSUE THREAD

**Issue by samertm** [cure53/DOMPurify#129]
Following up with https://github.com/cure53/DOMPurify/issues/61.

How much work would it take to run DOMPurify's test suite with node.js and jsdom? I'd be willing to help out.

**Comment by cure53** [comment]
Good question :) What exactly do you have in mind?

**Comment by samertm** [comment]
Ideally, one of the `customLaunchers` from test/karma.conf.js would be 'node_js_with_jsdom'. I have no idea how that works, and it's probably not worth doing unless jsdom passes the full test suite.

So I guess the best place to start is running the test suite with node.js. I some trouble adapting @Joris-van-der-Wel's script (https://joris-van-der-wel.github.io/DOMPurify-test-jsdom.js) to work with the new framework. I can continue working on that, but any pointers would be greatly appreciated!

**Comment by Joris-van-der-Wel** [comment]
I have not checked in a while, however previously all tests were passing in jsdom, except for:

* the KEEP_CONTENT option, 
* A few `[OverrideBuiltins]` tests. These tests failed because jsdom does not implement a few properties that the tests check for. However those properties are not used by dompurify.

I do not think anyone has made a karma plugin for jsdom. I am not sure if it would make much sense to make one, you would add a lot of useless overhead.

Something I like to do is that I define two tasks using grunt. One task tests jsdom, the other task runs browserify and then karma for firefox, chrome, etc. (I am working on setting this up for jsdom itself too). A pattern I often use is this (example is using mocha):

```javascript
describe('my dom lib', function() {
	var document;
	var window;

	// `beforeEach` could also be used, this would give you a fresh document for each test.
	before(function() {
		// ( browserify automatically defines `global` to be `window` )
		document = global.document || require('jsdom').jsdom('<html/>');
		window = document.defaultView;
	});

	it('should do something fancy', function() {
		var myLib = new MyLib(window);
		if (myLib.foo(10) !== 20) {
			throw Error('uh o');
		}
	});
});
```

**Comment by cure53** [comment]
Is there anything we can do at this point to help?

**Comment by Joris-van-der-Wel** [comment]
Help with jsdom, or help with getting the test suite to work?

**Comment by cure53** [comment]
With getting the test suite to work :)

**Comment by samertm** [comment]
I found karma-jsdom-launcher and tried to get it to work with the diff below. Running it errored out with with "Cannot read property 'ownerDocument' of undefined at /home/samer/src/DOMPurify/test/purify.min.spec.js:63". Line number "63" doesn't exist in purify.min.spec.js, though, so it's hard to tell what test failed.

Diff:

```
diff --git a/package.json b/package.json
index 61bb57e..ae797aa 100644
--- a/package.json
+++ b/package.json
@@ -24,6 +24,7 @@
     "karma-firefox-launcher": "^0.1.6",
     "karma-fixture": "^0.2.5",
     "karma-html2js-preprocessor": "^0.1.0",
+    "karma-jsdom-launcher": "^1.0.1",
     "karma-json-fixtures-preprocessor": "0.0.5",
     "karma-qunit": "^0.1.8",
     "karma-webpack": "^1.7.0",
diff --git a/test/karma.conf.js b/test/karma.conf.js
index 03d4394..2c6c5dd 100644
--- a/test/karma.conf.js
+++ b/test/karma.conf.js
@@ -131,7 +131,8 @@ module.exports = function(config) {
       'bs_win81_opera_31',
       'bs_win7_firefox_12',
       'bs_win81_chrome_22',
-      'bs_win10_edge_12'
+      'bs_win10_edge_12',
+      'jsdom'
     ],
 
     browserDisconnectTimeout: 10000,
@@ -144,7 +145,8 @@ module.exports = function(config) {
       'karma-chrome-launcher',
       'karma-browserstack-launcher',
       'karma-firefox-launcher',
-      'karma-qunit'
+      'karma-qunit',
+      'karma-jsdom-launcher'
     ],
 
     singleRun: true,
```

Test command + output

```
samer@samer-dell:~/src/DOMPurify$ ./node_modules/.bin/karma start test/karma.conf.js --browsers jsdom --single-run
16 12 2015 16:57:48.595:WARN [watcher]: Pattern "/home/samer/src/DOMPurify/bower_components/jQuery/dist/jquery.js" does not match any file.
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.9
Time: 7ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 2752581bd28320c1eeaf
Version: webpack 1.12.9
Time: 194ms
                  Asset     Size  Chunks             Chunk Names
   test/config/setup.js  4.29 kB       0  [emitted]  test/config/setup.js
test/purify.min.spec.js   296 kB       1  [emitted]  test/purify.min.spec.js
    test/purify.spec.js   343 kB       2  [emitted]  test/purify.spec.js
chunk    {0} test/config/setup.js (test/config/setup.js) 217 bytes
    [0] ./test/config/setup.js 217 bytes {0} [built]
chunk    {1} test/purify.min.spec.js (test/purify.min.spec.js) 109 kB [rendered]
    [0] ./test/purify.min.spec.js 306 bytes {1} [built]
    [1] ./dist/purify.min.js 10.6 kB {1} [built]
    [2] ./test/test-suite.js 20 kB {1} {2} [built]
    [3] ./test/fixtures/expect.js 77.7 kB {1} {2} [built]
chunk    {2} test/purify.spec.js (test/purify.spec.js) 127 kB [rendered]
    [0] ./test/purify.spec.js 301 bytes {2} [built]
    [2] ./test/test-suite.js 20 kB {1} {2} [built]
    [3] ./test/fixtures/expect.js 77.7 kB {1} {2} [built]
    [4] ./src/purify.js 29.2 kB {2} [built]
webpack: bundle is now VALID.
16 12 2015 16:57:48.866:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
16 12 2015 16:57:48.870:INFO [launcher]: Starting browser jsdom
16 12 2015 16:57:49.095:INFO [Node.js (linux; U; rv:v4.2.3)]: Connected on socket k4ObQpLmzEurrwhvAAAA with id 92131991
Node.js (linux; U; rv:v4.2.3) ERROR
  Cannot read property 'ownerDocument' of undefined
  at /home/samer/src/DOMPurify/test/purify.min.spec.js:63


Node.js (linux; U; rv:v4.2.3) ERROR
  Cannot read property 'ownerDocument' of undefined
  at /home/samer/src/DOMPurify/test/purify.spec.js:1262
```

**Comment by cure53** [comment]
Maybe tell it first to run with the uncompressed source - that should make the debugging easier.

**Comment by Joris-van-der-Wel** [comment]
One downside of `karma-jsdom-launcher` is that you will be using an older version of jsdom. That library lists jsdom as its dependency and pins it at version 6.x.x, it would have been better if it had listed jsdom as a peerDependency, so that you can specify the version yourself. If I use the jsdom launcher in the same way as you did, I get the same error. However if I force the latest version of jsdom (7.2.1) to be loaded, the results are much better and it actually starts to run tests (`rm -rf node_modules/jsdom && npm i jsdom@latest`). 

There is still something fishy going on though, my result is `Executed 254 of 1156 (36 FAILED) ERROR`. The last time I was working on jsdom support for DOMPurify, no tests were skipped and the failures were in the single digits.

Another downside is that it can make things a bit harder to debug (as you have noticed).

Something else that would also be useful to test is that you can use DOMPurify + jsdom without allowing script execution, you do not even have to use `jsdom.env()`. However you will not be able to test that using a karma launcher:

```javascript
var document = require('jsdom').jsdom('', {
    FetchExternalResources: false,
    ProcessExternalResources: false
});
var DOMPurify = require('dompurify')(document.defaultView);
console.log(DOMPurify.sanitize('<script>alert("hi");</script><p>hello</p>'));
```

**Comment by cure53** [comment]
Hi all, is this still a WIP? if not I'd suggest to close the ticket for inactivity.

**Comment by samertm** [comment]
You can close this for now, things got busy at work and this fell
off my plate.


On Thu, Jan 14, 2016, at 06:50 AM, Cure53 wrote:
> Hi all, is this still a WIP? if not I'd suggest to close the ticket
> for inactivity.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/cure53/DOMPurify/issues/129#issuecomment-171662738

**Comment by cure53** [comment]
Aye, thanks :)
