### ISSUE TITLE
purify environment check error in electron(http://electron.atom.io/) environment

### ISSUE THREAD

**Issue by tosscaster** [cure53/DOMPurify#134]
} else if (typeof module !== 'undefined') { 
==> replace with
    } else if (typeof exports !== 'undefined' && this.exports !== exports) {

in electron environment 'module' is defined.

by : http://www.timetler.com/2012/10/13/environment-detection-in-javascript/

**Comment by cure53** [comment]
Hi @tosscaster - the suggested patch looks okay to me.

@fhemberger What do you think?

**Comment by fhemberger** [comment]
Checking for `exports` instead of `module` is okay.

An [alternative method](https://github.com/umdjs/umd/blob/master/templates/commonjsStrictGlobal.js#L25) can be found in the Universal Module Definition example, where the original code of this check came from (though I haven't tested if this also works fine for electron).

**Comment by cure53** [comment]
Thanks, @fhemberger!

@tosscaster then I am happy to receive a PR for this change :)

**Comment by cure53** [comment]
Hi @tosscaster - I was wondering if that issue is still relevant for you. Happy to merge in a PR of yours if so. If not, I would propose to close this ticket.
