### ISSUE TITLE
Dangling markup signalling

### ISSUE THREAD

**Issue by dnkolegov** [cure53/DOMPurify#164]
It would be great if DOMPurify can signal about dangling markup injection like it does for removed nodes.

For example:
```
var dirty = "<img src='http://evil.com";
var clean = DOMPurify.sanitize(dirty);
DOMPurify.dangled
// true
```

Idea of fix is to check if `body.innerHTML` is empty before [return body](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L783) in `DOMPurify.sanitize`:

```
DOMPurify.dangled = false;
...
if (!body.innerHTML) {
    DOMPurify.dangled = true;
}
return WHOLE_DOCUMENT ? body.outerHTML : body.innerHTML;
```

Thanks.

**Comment by cure53** [comment]
Hmmm, I think this is outside our scope and hard to implement without regexes.

This might however be solvable with a few new hooks, same as #163, which is somewhat related. What do you think?

**Comment by dnkolegov** [comment]
As I understand DOMPurify does not implement protection against `Dangling markup injection` specially: there are no such seprate checks in the code. 

Protection is implemented automatically due to browsers' DOMParser:
`<img src='1` will be parsed to `<html><body></body></html>`. In this case test a simple: we should check existence of  `body`'s nodes. 
If you talk about regexes, probably it means, that there are another cases with dangling markup injections that can not be detected this way.

**Comment by cure53** [comment]
Exactly. For us, dangling markup injections are not an issue, because the DOM we create just kills all that dangles ;) If someone injects an unclosed tag? It disappears. If someone injects an unclosed textarea or button? It will close itself. Same for style, script (if allowed) and all others. Even option elements (our favorite ones for this kind of attack).

Meaning, there is no attack that would actually work. None, that we are aware of. If there was one: bug ticket, immediate fix, security release :D

The only thing we could do here is detect the _possibility_ of an attacker using dangling markup. And that's outside our scope of features and security promises. 

But - super easy to implement for you in your own script using DOMPurify I guess.

**Comment by dnkolegov** [comment]
Agree. The bug can be closed.

P.S. Does the following code make sense to detect injected dangling markup?

```
var dirty = getData();
var dangled = false;
var clean = DOMPurify.sanitize(dirty);
if (dirty !== '' and clean === '') {
    dangled = true;
}

```

**Comment by cure53** [comment]
Hmmmm. No, not reliably. cases that would break this check:

* `dirty = '<script>alert(1)</script>'` you're not checking if `DOMPurify.removed` is empty of not
* `dirty = '<b><img src="//evil.com/'` because `clean` would not be empty

**Comment by cure53** [comment]
I think there is one way of doing it: You have to "undangle" and then check twice.

You could append the following string to the markup you want to check: `"'>` (might have to be extended of course). Then you sanitize both the original and the appended version. You also create a white-list that contains *no* elements. Then you compare the number of removed elements. If it is uneven, dangling might be likely.

I think this could work with some refinement.

**Comment by dnkolegov** [comment]
Thanks. Interesting.
I will implement and test this and then let you know.

**Comment by cure53** [comment]
Cool :)
