### ISSUE TITLE
Question: Removing empty nodes

### ISSUE THREAD

**Issue by renarsvilnis** [cure53/DOMPurify#169]
Hi,
wondering is it possible to configure `DOMPurify` to remove empty nodes?

My current config (*below*), leaves `<h3><p></p></h3><h3></h3>` after purifying, but I would like to remove them.

```javascript
const config = {
  ALLOWED_TAGS: ['h3', 'p', 'i', 'b', 'em', 'strong', '#text'],
  ALLOWED_ATTR: ['target', 'href'],
  KEEP_CONTENT: false,
  ALLOW_DATA_ATTR: false
};
```

**Comment by cure53** [comment]
Heya, that is definitely possible with a hook. You need some pointers on where and how to start?

**Comment by renarsvilnis** [comment]
@cure53 that would be great.

**Comment by cure53** [comment]
Check out this demo, there you can see, how to use a hook:

https://github.com/cure53/DOMPurify/blob/master/demos/hooks-demo.html

The hook of your choice would likely be `afterSanitizeElements`. You can, after an element has been sanitized, simply check if it contains any content or not - and if not remove it.

**Comment by cure53** [comment]
So, it worked for you? :) Maybe you want to share the code for a quick review - we could also add it to the demos.

**Comment by ThePendulum** [comment]
I am currently running into this issue as well.

I am familiar with the hooks (although the lifecycle and arguments passed to each could be explained in more detail, imo, for example the difference between `afterSanitizeElements` and `beforeSanitizeAttributes`). I added an `afterSanitizeAttributes` hook (since I am assigning illegal attributes to certain nodes), which allows me to find and modify nodes, but I would like to know how you would go about the actual discarding itself. The return value appears to be ignored, so is there a property in the likes of `keepAttr` that instead applies to the entire node?

Thank you!

**Comment by cure53** [comment]
Hmm, not sure if I understand, what is the actual problem?

**Comment by ThePendulum** [comment]
I solved mine now, but the documentation is somewhat lacking. It mentions that you can modify the node and then return it, so to me it stood to reason that returning null or false removes the node. However, it seems that returning doesn't really affect anything at all. Even if you modify a node or attribute, the changes are applied regardless of what you return.

Some elaboration on what happens between each hook would've been helpful as well, as it's not self-explanatory how the state changed between, for example, `afterSanitizeElements` and `beforeSanitizeAttributes`. It also seems reasonable to remind people that calling node.remove() from a hook will indeed remove the node from the output.

**Comment by cure53** [comment]
Gotcha, and you are right, we need to add more comments and documentation here.
