### ISSUE TITLE
Sanitizing reverse order of properties

### ISSUE THREAD

**Issue by lonewarrior556** [cure53/DOMPurify#271]
> This issue proposes a [bug/feature] which...

Is it possible to NOT reverse the order of properties inside elements?

ie.
```
console.log(sanitizeObject('<svg><rect height="1000" width="1000" y="0" x="0"></svg>'))
<svg><rect x="0" y="0" width="1000" height="1000"></rect></svg>

```

this makes it very difficult have proper testing

**Comment by cure53** [comment]
This is something the browsers do, as far as I can see. We don't shuffle or re-order attributes manually.

What is being made difficult exactly?

**Comment by lonewarrior556** [comment]
When units testing and mocking api's you often check the params that were passed with something like       `assert.deepStrictEqual(data, payload)` this fails if the string changes

**Comment by cure53** [comment]
Gotcha, we have the same problem with our test-suite and need to have four strings for four browsers sometimes because of that.

See here https://github.com/cure53/DOMPurify/blob/master/test/fixtures/expect.js#L32

But then again, not our code - the browsers (especially MSIE) rewrite the HTML and especially SVG and change the attribute order on their own. So, not sure if we can help here.

**Comment by lonewarrior556** [comment]
Got it. Thanks. Closing.
