### ISSUE TITLE
Infinite loop while iterating nodes

### ISSUE THREAD

**Issue by choumx** [cure53/DOMPurify#285]
Hit this while trying out the suggested solution in #185.

Repro case:
```html
<!doctype html>
<html>
  <head>
    <script type="text/javascript" src="node_modules/dompurify/dist/purify.js"></script>
    <script> 
      DOMPurify.sanitize('<template><p></p></template>', {
        'ALLOWED_TAGS': ['template', 'p'],
        'WHOLE_DOCUMENT': true, 
        'RETURN_DOM_FRAGMENT': true,
      });
    </script>
  </head>
</html>
```

The node iterator seems to bounce endlessly between the `head` and `body` element. 

Can be fixed by adding `'html', 'head', 'body'` to `ALLOWED_TAGS`.

**Comment by cure53** [comment]
@choumx Here is a first workaround that yields the expected results and doesn't hang:

```html
<!doctype html>
<html>
  <head>
    <script type="text/javascript" src="../purify.js"></script>
    <script> 
      var sanitized = DOMPurify.sanitize('<template><p></p></template>', {
        'ALLOWED_TAGS': ['template', 'p'],
        //'WHOLE_DOCUMENT': true,
        'FORCE_BODY': true,
        'RETURN_DOM_FRAGMENT': true,
      });
      console.log(sanitized);
    </script>
  </head>
</html>
```

We are looking for the loop now and will commit a fix soon.

**Comment by cure53** [comment]
Okay, we pushed a fix for the loop. 

The problem here was that the settings `ALLOWED_TAGS and `WHOLE_DOCUMENT` were colliding. We now override `ALLOW_TAGS` and allow `<html>`, `<head>` and `<body>` if WHOLE_DOCUMENT is set to true. This makes sense since we would return a crippled document anyway afterwards if those got removed.

The best setting for your case however is the relatively new `FORCE_BODY` and mentioned above. It should be faster and better suited for your situation. Please let me know if that works for you!

**Comment by choumx** [comment]
It works. 🎉  

Thanks for the tip on `FORCE_BODY` and super fast turnaround!

**Comment by cure53** [comment]
yw :)
