### ISSUE TITLE
Make DOMPurify work in Node.js

### ISSUE THREAD

**Issue by fhemberger** [cure53/DOMPurify#29]
Regarding issue #26 and #27, I originally held back Common JS style exports and publishing on npm on purpose, as DOMPurify doesn't run on a pure Node.js environment (it does client side with Browserify).

I'm still looking for a way to get it to work on Node.js as well. jsdom [lacks DOM Level 2 Traversal methods](https://github.com/tmpvar/jsdom/issues/317) like `createNodeIterator` at the moment, which DOMPurify uses internally.

What's currently missing:
- [x] `document.implementation.createHTMLDocument`  
  (polyfilled with `return jsdom('<html><body></body></html>');`)
- [x] `window.NodeFilter (extracted the properties needed for DOMPurify from the spec)
- [ ] `document.createNodeIterator(root, whatToShow, filter, entityReferenceExpansion)`
- [ ] `NodeIterator.nextNode()` implementation
- [ ] Setter method for `document.body.outerHTML`

**Comment by wtfuii** [comment]
+1 for this feature..

**Comment by Joris-van-der-Wel** [comment]
jsdom 5.1.0 supports NodeIterator: https://github.com/tmpvar/jsdom/pull/1092
There are still other issues though, such as `firstElementChild`

**Comment by fhemberger** [comment]
Thanks, I read the announcement (but hadn't notice the version has already been released).
I hope to find the time soon to look into this topic again. Sorry this takes so long, but fiddling around with a DOM implementation in Node is really messy. ;)

**Comment by Joris-van-der-Wel** [comment]
[jsdom 5.2.0](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#520) has many fixes to make dompurify work. Most html snippets can now be "purified" properly.
Although I have to load dompurify as a script using jsdom.env because dompurify uses a lot of globals. It would be great if I could instantiate dompurify by passing it a `Window`.

There are still a few test cases failing though, which would require more work in jsdom. One example is that jsdom currently throws an exception if an attribute is set with an invalid name: `foo.innerHTML = "<img id/=' >"`. The spec says that resolving parser errors is optional, but it is of course not how the browsers behave. The result is that dompurify is not able to clean up such snippets.

**Comment by Joris-van-der-Wel** [comment]
Above has been fixed. There are now 13 failing test cases.
Additional stuff to fix in jsdom:

* A few test cases with svg tags fail, the output looks safe, but it is not what the test cases expect
* stub or implement adoptNode
* stub or implement activeElement
* Do not throw if the `style` attribute contains invalid CSS
* Implement insertAdjacentHTML (required if you want to use KEEP_CONTENT)

**Comment by fhemberger** [comment]
Thanks @Joris-van-der-Wel for digging into this, looks like we're getting closer.
Unfortunately, I'm pretty occupied at the moment, so I'm not able to dive into the jsdom code right now to  implement the missing features. :disappointed:

**Comment by cure53** [comment]
A quick question: I think we are close to the next release. Should we go ahead or wait for you guys? Not sure how far this ticket is in total, thus asking :)

**Comment by fhemberger** [comment]
No, don't wait for me. Just go ahead and release it. Node support would be a major version increment anyway.

**Comment by Joris-van-der-Wel** [comment]
As for releasing:
I do not think that any XSS attempts will get through if you use jsdom with these unresolved issues. The effects of these issues are:

* `adoptNode`, `activeElement` and maybe others that are not in the test cases may get clobbered if you only filter using jsdom. These are not causing XSS leaks.
* Invalid CSS in style tags will throw. For example if DOMPurify is used in a node http server, it would give clients a 500 error instead of the sanitized html.
* The KEEP_CONTENT option does not work at all

The only thing I am not sure about yet are the 2 cases (87 and 173) that fail with svg content. I have not looked at those extensively. Perhaps all those need are an additional "expected" value in the test case itself.

Here is the output of the test cases: https://joris-van-der-wel.github.io/DOMPurify-04d7218-on-jsdom-5.4.0.html and here is the script I used to generate this https://joris-van-der-wel.github.io/DOMPurify-test-jsdom.js

**Comment by Joris-van-der-Wel** [comment]
So if none of those issues can cause a security issue, I would say, release it

**Comment by dhardtke** [comment]
So will 0.6.4 support NodeJS?

**Comment by Joris-van-der-Wel** [comment]
It supports iojs. (nodejs will be supported in the near future because iojs and nodejs are merging).

Try this:

```bash
npm install cure53/DOMPurify jsdom
```

```javascript
var document = require('jsdom').jsdom();
var dompurify = require('dompurify')(document.defaultView);
console.log(dompurify.sanitize(`
        hell <script>alert("hi");</script>
        <div onclick="alert(123);">
                o
        </div>
        world
        <img id="createElement">
`));
```

**Comment by fhemberger** [comment]
I'm so grateful for your help so we finally got this out. Thanks!

**Comment by fhemberger** [comment]
I haven't had the time for testing it, but can we close this issue now?

**Comment by Joris-van-der-Wel** [comment]
Well, enabling KEEP_CONTENT has no effect now. Beyond that, I can imagine wanting to add a test runner in DOMPurify for jsdom (also see #61).

And the readme will need updating

**Comment by fhemberger** [comment]
Updated the README just now: 6b0c682116f61927b8e7a43ea3e973438c5179dc.
I'm closing this issue now and create a new issue for KEEP_CONTENT.

**Comment by CaptainN** [comment]
In case anyone else comes looking - to make current `jsdom` work (Feb 2019):

```js
import { JSDOM } from 'jsdom'
import DOMPurify from 'dompurify'
const { window } = new JSDOM('<!DOCTYPE html>')
const domPurify = DOMPurify(window)
console.log(domPurify.sanitize(`
        hell <script>alert("hi");</script>
        <div onclick="alert(123);">
                o
        </div>
        world
        <img id="createElement">
`));
```

**Comment by kkomelin** [comment]
@CaptainN Thanks for your solution. 
I've gone further and created an isomorphic wrapper which allows using DOMPurify on both frontend and backend seamlessly https://github.com/kkomelin/isomorphic-dompurify
I would appreciate your feedback on the wrapper.

**Comment by EddyVinck** [comment]
I just stumbled upon this problem. I found a lightweight alternative for DOMPurify that works in Node: https://github.com/leizongmin/js-xss

```js
import xss from 'xss';

export function sanitizeText(string) {
  // only include whitelisted tags, remove the others
  return xss(string, { whiteList: ['b', 'i', 'strong'], stripIgnoreTag: true });
}
```

It has to be lightweight because I'm using it with server-side rendered React, which runs in Node first but then runs in the browser.

**Comment by kkomelin** [comment]
@EddyVinck There are a few xss filtering packages on NPM, you're free to use any of them. 

What led me to DOMPurify is this presentation [Building Secure React Applications by Philippe De Ryck](https://www.youtube.com/watch?v=O91hJJ5KMLs). Since you're working with React, it may interest you too.

**Comment by etiennejcharles** [comment]
Well seems like a port was created 2 months ago
https://github.com/kkomelin/isomorphic-dompurify#readme
