### ISSUE TITLE
HTML without ending tags nests the next tag

### ISSUE THREAD

**Issue by zuber7** [cure53/DOMPurify#330]
@cure53 

### Background & Context

Cleaning HTML without proper ending tags.

### Bug

Dompurify nests the next tag if the current node does not have proper ending tags.

#### Input

```
<div id="test1" />
<div id="test2" />
```

#### Given output

```
<div id="test1">
<div id="test2"></div></div>
```

#### Expected output

```
<div id="test1"></div>
<div id="test2"></div>
```

### Feature

Dompurify should not change the html structure

**Comment by tomholub** [comment]
This is probably the work of the browser anyway, but the handling looks correct to me. Imagine you are the parser:
 - encounter first div open
 - encounter second div open (inside the first div, because the first one wasn't closed)
 - encounter the end

What do you do now? Probably close the inner div, then close the outer one.

**Comment by cure53** [comment]
I agree, this is expected behavior. Not much we can do here without breaking other things.
