### ISSUE TITLE
Applicability of SAFE_FOR_JQUERY option with other libraries, specifically lit-html

### ISSUE THREAD

**Issue by lastmjs** [cure53/DOMPurify#344]
### Background & Context

The README mentions that if you use jQuery's `elm.html()`, then you should use the dompurify option `SAFE_FOR_JQUERY`. This gives me a little bit of concern, as I'm using a relatively new library called [lit-html](), and I'm not sure if the issues with jQuery's `elm.html()` might apply to `lit-html`.

### Feature

I'd like some clarification/explanation on why jQuery's `elm.html()` is insecure. If there were a little more explanation, I might be able to determine for myself when my use of dompurify is safe or not. It seems strange to have just one library out of many that has this one specific issue. Could there be other libraries with the same issue?

**Comment by cure53** [comment]
Heya, sure :)

We consider jQuery's HTML implementation insecure because they parse HTML as string before assigning it to the DOM. So, when `html()` is being used, different things happen compared to when `ìnnerHTML` is being used.

One XSS we once had was caused by this and looked like that: https://github.com/cure53/DOMPurify/blob/master/test/fixtures/expect.js#L200

This snippet above is safe when used without jQuery. And unsafe when used with jQuery's `html()` or anything that relates to that method.

It could be that other libraries have issues too, if so, we'd love to know :D

**Comment by lastmjs** [comment]
Thank you, I'll look into lit-html and compare to what you described above

**Comment by cure53** [comment]
Cool, thanks. 

With jQuery we made this call because a) everyone uses it and b) people using `sanitize()` first and then feeding the result to `html()` was seen too many times in the wild.
