### ISSUE TITLE
Name/autofocus attributes are removed from input element

### ISSUE THREAD

**Issue by piotrmitrega** [cure53/DOMPurify#364]
### Input

```html
<input class="form-control" name="name" type="text" placeholder="Title" autofocus required>
```

#### Given output

```html
<input required placeholder="Title" type="text" class="form-control">
```

#### Expected output

```html
<input class="form-control" name="name" type="text" placeholder="Title" autofocus required>
```

What's the reason of removing those two attributes?

**Comment by cure53** [comment]
Heya, sure!

`name` is removed because it likely collides with an internal DOM property. This is rated as a possible DOM clobbering attack and hence stripped. You can navigate around that by disabling DOM clobbering checks:

`var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});`

`autofocus` is often used to steal form data from unaware users - hence we block it by default. You can re-enable it by using:

`var clean = DOMPurify.sanitize(dirty, {ADD_ATTR: ['autofocus']});`

**Comment by piotrmitrega** [comment]
Thank you for fast and detailed answer! 👏 

PS: not sure if a bug, but FYI `name` is not removed from, e.g this element:

```html
<input placeholder="Description" type="text" name="description" class="form-control">
```

**Comment by cure53** [comment]
Most welcome :) 

And yes, here, DOMPurify finds no collision with existing DOM properties. So it is considered fine. This is the code taking care of that check:

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L726
