### ISSUE TITLE
ASK: how to allow immediate text  after "<" to be bypassed

### ISSUE THREAD

**Issue by diondirza** [cure53/DOMPurify#403]
I have a case, that users sometimes put this kind of words.

#### Input
```
L <R  left hand is not as strong as right hand
```

#### Given output

```
L 
```

#### Expected output
```
L <R  left hand is not as strong as right hand
```

How do you allow with that kind of case? Not just L <R or vice versa, yet sometimes random text can happen.

**Comment by cure53** [comment]
As this would be detected as an R element by the browser (or as whatever letter follows after the "<"), we would not be able to do anything here to allow this.

**Comment by cure53** [comment]
Wondering, is HTML even expected in those texts? Would simply using encoding be an option?

**Comment by diondirza** [comment]
HTML should not be expected here actually, yet our pen tester recommends all our input should have been sanitized. Since the logic used in this library is by using a whitelist, is it possible to use a blacklist approach? 

```
DOMPurify.sanitize(dirty, { useBlacklist: true });
```

Last option probably do encoding before sanitizing.

**Comment by cure53** [comment]
I see. I think the pentester's recommendation is not optimal: If no HTML is needed, no sanitization is needed as well. For plaintext, we would recommend **encoding only**. Only in cases where HTML is expected, sanitization needs to take place.

Otherwise you treat a common cold with a powerful flu vaccine, which would not make sense :)
