### ISSUE TITLE
Why Sanitized HTML is not recommended to load using Jquery element.html()

### ISSUE THREAD

**Issue by vakhariasohil** [cure53/DOMPurify#406]
> This issue proposes a [bug, feature] which...

### Background & Context

The resulting HTML can be written into a DOM element using innerHTML or the DOM using document.write(). That is fully up to you. '**But keep in mind, if you use the sanitized HTML with jQuery's very insecure elm.html() method**', then the SAFE_FOR_JQUERY flag has to be set to make sure it's safe! Other than that, all is fine.

Why Sanitized HTML is not recommended to load using Jquery element.html()?

#### Input

Some HTML which is thrown at DOMPurify.

#### Given output

The output given by DOMPurify.

#### Expected output

The expected output.

### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
The problem is that jQuery, upon using `elm.html()` _changes_ the HTML structure before mapping it to `innerHTML`. This is an anti-pattern but they still do it.

In other words, what is safe in the browser is no longer safe with jQuery.

Because of that, we need to have some extra magic to prevent XSS. By activating the `SAFE_FOR_JQUERY` flag, you activate the extra magic and things will be safe again :)

**Comment by cure53** [comment]
Here is an example by the way :) 
https://github.com/cure53/DOMPurify/blob/master/test/fixtures/expect.js#L202

Hope that helped, please re-open if there is any questions left.

**Comment by vakhariasohil** [comment]
Gotcha.!! Thanks for the update

**Comment by cure53** [comment]
:+1: :)
