### ISSUE TITLE
sanitize() function seems to reverse the order of the attributes

### ISSUE THREAD

**Issue by asatgs** [cure53/DOMPurify#42]
It looks like the order of attributes is being reversed in the output from `sanitize()`.
While from from the point of view of functionality it makes no difference, it is something that will trip over people that are writing unit tests using this library.

That said, thank you very much for this product!

**Comment by cure53** [comment]
Yes and no :) In some browsers it appears like that, in others it doesn't. 
Check for example the differences in IE and FF:

```html
input:
<a href="1" class="2" id="3"></a>

output FF:
<a id="3" class="2" href="1"></a>

output IE:
<a class="2" id="3" href="1"></a>
```

We're aware that the order of attributes is being changed - but never saw it as a problem since browsers do the same here and there. If you believe it might turn out o become a security problem, we can have a closer look into it.

**Comment by asatgs** [comment]
Interesting. I haven't really assessed the security impact of this, but it seems to be harmless. I ran into this accidentally while putting together some unit tests that run in PhantomJS. Thank you for your reply!

**Comment by cure53** [comment]
Sure :) Closing this for now, happy to work on it if there's any security impact or breakage!
