### ISSUE TITLE
Named export API

### ISSUE THREAD

**Issue by aminya** [cure53/DOMPurify#426]
It would be nice if `sanitize` was also a named export, so we could do tree shaking with rollup.

**Comment by tdeekens** [comment]
Thanks for reporting. Due to the underlying setup and structure of DOMPurify I don't think that it's possible to export sanitize in a named way. There have been discussions around it but it would require some substantial rearchitecture of the library code. 

I don't see us focussing on that right now cause it's would likely be breaking. If you however see a way to enable this without a breaking change I can only encourage you to open a PR or suggest a solution here :)

**Comment by cure53** [comment]
Yup, I fully agree with @tdeekens :D
