### ISSUE TITLE
Dompurify allows XSS vulnerabilities 

### ISSUE THREAD

**Issue by rori4** [cure53/DOMPurify#466]
## Bug
The default configuration has vulnerabilities. I have tested dompurify against this xss list -> https://github.com/payloadbox/xss-payload-list and it has a lot of scripts that pass. I don't have the time to narrow them down but I think this should be investigated

I am switching to another library

**Comment by cure53** [comment]
I think you are wrong with this assessment, there is nothing to investigate. 

That list is known and we cover all cases that would lead to script execution. If you manage to however cause a bypass here (or any other setup where DOMPurify runs), then we will fix it faster than light: https://cure53.de/purify

> I am switching to another library

Bye bye.

**Comment by rori4** [comment]
OK, sorry I think its my implementation of the package. On the test website it works properly

**Comment by cure53** [comment]
To explain the context a little bit: 

That list is great but it assumes that the server (or something similar) transforms the user input after sanitization, sometimes a bit, sometimes a lot. Check for example the vectors using multiple rounds of URL-encoding. Those would _never_ execute unless the server or anything else transforms the data _after_ sanitization.

DOMPurify however uses the browser (or jsdom, if run on the server) to parse the incoming user data. It then turns the HTML into a DOM, sanitizes the DOM and then returns the remaining markup that is deemed to be safe. We believe this is the best way of doing it. Needless to say, if it receives a double-encoded string of HTML, it does nothing with it. Because that string does nothing.

So, the assumption we operate on, successfully so, is: Sanitization is the final step before actually using the user controlled HTML. This is also documented here: https://github.com/cure53/DOMPurify#is-there-any-foot-gun-potential

If the markup we sanitize doesn't look fishy in the instrumented browser logic we use for sanitization, it will likely do nothing in the actual browser where it is used right after sanitization.

To conclude. If you manage to find an actual bypass (or even several ones), you don't have to stop using our library but rather report it to us, get some nice bug bounty and we will fix the bypass as quickly as we can.
