### ISSUE TITLE
<noscript> sanitization is confusing

### ISSUE THREAD

**Issue by infeng** [cure53/DOMPurify#544]
dompurify version: `2.2.9`

Filtering `<noscript>` performs differently in different scenarios 

### only `<noscript>` tag
**input**
```
<noscript>
  <span>This is content of span</span>
</noscript>
```
**output**
```
<span>This is content of span</span>
```

### not only `<noscript>` tag
**input**
```
<div>
  <noscript>
    <span>This is content of span</span>
  </noscript>
</div>
```
**output**
```
<div></div>
```

**Comment by cure53** [comment]
Confusing indeed, but it's the browser that causes that.

In case the `<noscript>` is not wrapped inside another element, the browser sends it to the `<head>` element. The included `<span>` however remains in the body as it is being parsed.

In case the `<noscript>` _is_ wrapped inside another element, the browser thinks, "oh, you can stay here, no need to send you into the head section" and then removed it because it is forbidden. That also kills the `<span>`.

So, we cannot do much here unless this becomes a security issue :) Does that make sense?

**Comment by cure53** [comment]
Check for example those results:

```javascript
DOMPurify.sanitize('<noscript><span>This is content of span</span></noscript>');
DOMPurify.sanitize('111<noscript><span onclick=1>This is content of span</span></noscript>');
DOMPurify.sanitize('<noscript><span onclick=1>This is content of span</span></noscript>', {FORCE_BODY: true});
```
That shows a bit what is happening here.

**Comment by infeng** [comment]
Thanks for your reply, I get it. 
In addition, I find that the performance of `2.0.17` is not consistent with what you said, here is the [test link](https://codesandbox.io/s/white-darkness-pxh6q?file=/src/App.js), is there any change after `2.0.17` version?
```jsavascript
DOMPurify.sanitize('<noscript><span onclick=1>This is content of span</span></noscript>', {FORCE_BODY: true});
// output
// <span>This is content of span</span> 
```

**Comment by cure53** [comment]
That is correct. Since 2.0.17, the `<noscript>` element has been added to this lost for mXSS reasons:

https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L262
