### ISSUE TITLE
[Question] Why are `iframe`s removed by default?

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#566]
I was just wondering, why are `iframe`s not whitelisted by default? Are the only concerns clickjacking and phishing, or are there other vulnerabilities I'm unaware of?

**Comment by cure53** [comment]
Because they are too powerful and bring too many privacy and security risks - especially since there are lots of moving parts with sandbox, srcdoc, etc. etc.

Lastly, they are rarely _needed_ in user controlled HTML. Unless you have some crazy edge case, you don't want your users to inject iframes into your website.

**Comment by GrantGryczan** [comment]
Privacy and security risks like what? I do have a use case, which is that I want people to be able to embed arbitrary HTML5 games and animations on my website without having to manually and continuously verify every single one.

**Comment by GrantGryczan** [comment]
Also, it's worth noting I'm not converting the output to a string to concatenate or insert it into anything. I'm using the `RETURN_DOM_FRAGMENT` option, and then traversing the DOM object to convert it to a React node.

**Comment by cure53** [comment]
For your use case, looking into Iframe sandbox might make sense, then folks should be able to run whatever content inside the iframe hosts on your website. Not sure how sanitization would be the way to go then though.

Lots of good pointers can be found here as well:
https://stackoverflow.com/questions/7289139/why-are-iframes-considered-dangerous-and-a-security-risk
