### ISSUE TITLE
`form`s are allowed by default?

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#571]
I was wondering, why are `form` elements allowed by default? I would think they would be bad since they can send requests to arbitrary locations using arbitrary HTTP methods, possibly without the user's knowledge (and possibly containing sensitive information in an input field). It's not personally a concern for my own use case, but I'm wondering why it's not a concern by default. Should it not be?

```html
<form method="post" action="https://example.com/malicious-endpoint">
    <p>A totally legitimate unknown error occurred.</p>
    <button type="submit">Retry</button>
</form>
```

**Comment by cure53** [comment]
As per our [Security Goals](https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model), we deem forms and anchors and everything alike to be okay. 

But, they are easy to deactivate via config if needs be :)

**Comment by GrantGryczan** [comment]
Hm, then I would think the same applies to `autofocus`, no? I would think that `form`s are much more dangerous than `autofocus`, especially since an element with `autofocus` wouldn't even be able to go anywhere without a `form` to submit it through or a script reading the data (which obviously would be sanitized out).

**Comment by GrantGryczan** [comment]
Sorry, I don't understand. I can't think of any examples that would allow a malicious user to utilize `autofocus` without using a `form`, script, or anything alike to capture the data.

Also, just wanna say thanks for consistently replying so quickly and being very helpful to me in general, both as a developer of this library and as a learning resource :)

**Comment by cure53** [comment]
Most welcome :) 

And yes, ultimately, the attacker needs something to catch the stolen keystrokes and send them somewhere. But, what if that part is already there in some other area of the page - an iframe or alike, which then works together with the sanitized markup?

The point is still, `autofocus` _enables_ attacks, so we nuke it by default. 

Forms however don't _enable_ attacks and - in the worst case - can only be used to exfiltrate data after the attack has been carried out. So, we decide to block what enables the attack rather than what might be part of the attack but is otherwise usually innocent.

**Comment by GrantGryczan** [comment]
Although I'm not sure I entirely agree, I see where you're coming from and now understand your point, so I'll go ahead and close this on the basis that you probably are a better judge of this than I am considering your experience.

**Comment by GrantGryczan** [comment]
(Not that it's a big deal anyway since anyone can easily change the config.)

**Comment by cure53** [comment]
Oki :) Thanks.
