### ISSUE TITLE
Requesting clarification on the SAFE_FOR_TEMPLATES option

### ISSUE THREAD

**Issue by SmilingJoe** [cure53/DOMPurify#698]
Not a defect, just requesting some additional clarification.

We have currently integrated DOMPurify into our application, and would like to get more clarification for the comment warning on the SAFE_FOR_TEMPLATES option.

```
// strip {{ ... }} and <% ... %> to make output safe for template systems
// be careful please, this mode is not recommended for production usage.
// allowing template parsing in user-controlled HTML is not advised at all.
// only use this mode if there is really no alternative.
var clean = DOMPurify.sanitize(dirty, {SAFE_FOR_TEMPLATES: true});
```

Why is this not recommended for production usage? Is this comment targeting applications where user input is directly routed onto page output?

Our current use is to help "sanitize" user input prior to it being sent to the back end as input for search processing. My assumption is that including the `SAFE_FOR_TEMPLATES: true` option would further sanitize the user input - preventing string of code from being submitted.

Can you provide a more specific example or define what a "template system" is in this context?

**Comment by cure53** [comment]
Heya, sure :)

Let's say there is a web application, that is running with, for instance, Vue.js where `{{constructor.constructor('alert(1)')()}}` _could_ lead to XSS. Let's also assume that, for whatever reason, user controlled HTML is actually parsed by Vue.js and that this XSS really exists.

We all know that _should_ not happen, but well, it does. We run into those kinds of findings line once or twice a month. 

If that is the case indeed and no systemic fix can be applied because reasons, then you can say "okay, I want all those injections be mitigated, let's activate this mode". Because then, DOMPurify will strip those expressions (or at least try really hard) and then your application might be a bit safer until the actual issue has been addressed.

That is why we have it, but not on by default.
