### ISSUE TITLE
DOMPurify strips off attributes with self-closing tags

### ISSUE THREAD

**Issue by djadmin** [cure53/DOMPurify#706]
It is found that the `DOMPurify` removes the attribute completely when it contains a self-closing tag.

#### Input
```html
<a href="https://example.com" data-title="hello<br/>world">Click</a>
```
#### Output

```html
<a href="https://example.com">Click</a>
```
#### Expected output

```html
<a data-title="hello<br/>world" href="https://example.com">Click</a>
```

### More details

The example use-case of the above code is to render tooltips with HTML content.

It was also noticed that if the attribute has non-self closing tags, they remain intact.

#### Example Input

```html
<a href="https://example.com" data-title="hello <span>world</span>">Click</a>
```
#### Output

```html
<a data-title="hello <span>world</span>" href="https://example.com">Click</a>
```

Would you consider this a bug? If not, would you explain the difference in behavior?

**Comment by cure53** [comment]
Not a bug, this is a protection against an mXSS Issue that would otherwise lead to a fully bypass.

You can likely work around that behavior with a hook, but might then lose the full extent of protection against several mXSS attack vectors. Here are several examples: https://github.com/cure53/DOMPurify/blob/main/test/fixtures/expect.js#L1086
