### ISSUE TITLE
Is there a way to keep id="body" in header tag ?

### ISSUE THREAD

**Issue by jiawei686** [cure53/DOMPurify#720]
### Background & Context

Is there a way to keep id="body" in header tag ? Other values are ok but 'body'.

#### Input

`sanitizer.sanitize('<h1 id="body">body</h1>'`

#### Given output

`'<h1>body</h1>'`

#### Expected output

`<h1 id="body">body</h1>`

**Comment by cure53** [comment]
Yup

`DOMPurify.sanitize(`<div id="body">hey</div>`, {SANITIZE_DOM: false});`

**Comment by jiawei686** [comment]
It seems that setting SANITIZE_DOM to false is a little more risky. Actually I'm confused why sanitizer will remove `id="body"`.

**Comment by cure53** [comment]
Because it will potentially tamper with the DOM property `document.body`, i.e. DOM Clobbering. In case you have elements that have IDs that are called like existing DOM properties, DOMPurify will detect this and prevent possible fallout.

In case that issue is not a risk for your application, it's safe to deactivate `SANITIZE_DOM`

**Comment by jiawei686** [comment]
Got it. Thanks a lot!
