### ISSUE TITLE
DOMPurify and Trusted Types - Clarification to Docs

### ISSUE THREAD

**Issue by cancan101** [cure53/DOMPurify#939]
This issue proposes an improvement to the README which clarifies how to use `DOMPurify.sanitize` along with `trustedTypes.createPolicy`, specifically when using Typescript.

### Background & Context

I am trying to create a `trustedTypes` policy and to use `DOMPurify.sanitize` in the `createHTML`. I am trying to do this in Typescript without resorting to `any`. 

I have read the docs here: https://github.com/cure53/DOMPurify?tab=readme-ov-file#what-about-dompurify-and-trusted-types and looked at other usage in GitHub and and am confused.

### Bug
This does not work (ie TS won't compile due to type issues):
```ts
window.trustedTypes!.createPolicy('default', {
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: true }),
});
```
whereas both of these work:
```ts
window.trustedTypes!.createPolicy('default', {
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: false }),
});
```
and
```ts
window.trustedTypes!.createPolicy('default', {
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: true }).toString(),
});
```

Should I just use one of those two options or is there a way to get this to work with `RETURN_TRUSTED_TYPE: true` without having to resort to `toString` or `any`?

### Feature

I suggest providing an more complete example in the docs of the correct usage.

**Comment by cure53** [comment]
Hmmmm, so the idea is that the policy method returns a string, correct?

**Comment by cancan101** [comment]
Returning a string loses some type information, namely that the string contains a _sanitized_ string. Is there any option within `trustedTypes` to allow the policy to accept a function that returns `TrustedHTML`?

**Comment by cure53** [comment]
I am not sure what you mean, could you clarify a bit more what you want to achieve, what does not work and whether this is a DOMPurify issue or a general TrustedType question?

What do you mean with "This does not work"?

**Comment by tosmolka** [comment]
I think [`CreateHTMLCallback`](https://www.w3.org/TR/trusted-types/#callbackdef-createhtmlcallback) from Trusted Types spec by design expects [`DOMString`](https://webidl.spec.whatwg.org/#idl-DOMString) return type, not [TrustedHTML](https://www.w3.org/TR/trusted-types/#trustedhtml) interface. So I don't think your first example is a bug, I think it works as expected. 

+1 on providing more complete example in the docs of the correct usage, this could certainly help others who are new to using DOMPurify with Trusted Types

**Comment by cure53** [comment]
Ooooh, okay, now this makes sense, thank you @tosmolka :slightly_smiling_face: 

About the README, happy to update, please define "more complete", what needs to be added?

**Comment by cure53** [comment]
@cancan101 Please let us know what you have in mind with a more comprehensive example, happy to update the README once we know (also feel free to send over a PR if that is easier).

**Comment by cancan101** [comment]
Perhaps something along the line of:

```ts
// to create a Policy in trustedTypes using DOMPurify
// RETURN_TRUSTED_TYPE: false is needed as createHTML expects a normal string rather than TrustedHTML
window.trustedTypes!.createPolicy('default', {
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: false }),
});
```

**Comment by cure53** [comment]
That works for me, thanks :smile:

**Comment by cure53** [comment]
We have updated the README, that should do the trick me believes?

**Comment by fulstadev** [comment]
Follow-up question, so if I do, as mentioned above: 

```
const myPolicy = window.trustedTypes!.createPolicy('default', {
  name: 'default',
  createScriptUrl: (to_check) => ['https://allowed.org'].includes(to_check) ? to_check : '',
  createScript: (to_check) => throw new Exception('Script Generation is Disallowed'),
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: false }),
});
```

...and then try to use that policy as the policy that DOMPurify should use via:

`DOMPurify.setConfig({TRUSTED_TYPES_POLICY : myPolicy });`

typescript complains that: 

`The types returned by createHTML(...) are incompatible .
Type string is not assignable to type TrustedHTML`

When I thus change the code above to: 

```
const myPolicy = window.trustedTypes!.createPolicy('default', {
  name: 'default',
  createScriptUrl: (to_check) => ['https://allowed.org'].includes(to_check) ? to_check : '',
  createScript: (to_check) => throw new Exception('Script Generation is Disallowed'),
  createHTML: (to_escape) =>
    DOMPurify.sanitize(to_escape, { RETURN_TRUSTED_TYPE: true }),
});
```

typescript complains that: 

`The types returned by createScriptURL(...) are incompatible .
Type string is not assignable to type TrustedScriptURL`

And I simply don't understand how I can return a `TrustedScriptURL` instance from a string.

If I return any `Trusted....` types via any of the policy methods, I always have to call `toString()` when I want to use the sanitized value, which also feels odd. Using `string`, as the initiator of this issue mentions, seems preferrable, but if I tell typescript that my policy methods return strings, I cannot specify that policy as the value of the `TRUSTED_TYPES_POLICY` config option due to the above-mentioned problem (because your `TRUSTED_TYPES_POLICY` config option is typed to return `Trusted...` instance types in `/dist/purify.es.d.mts`.

It would be really helpful if you could provide a concrete example in your docs on how you're supposed to implement a custom trusted types policy in typescript with your package and use that policy as the `TRUSTED_TYPES_POLICY` for any `DOMPurify.sanitize()` call ?
