### ISSUE TITLE
The MAX_NESTING_DEPTH remove contents issue has not been resolved.

### ISSUE THREAD

**Issue by kakao-bishop-cho** [cure53/DOMPurify#966]
> This issue proposes a [bug, feature] which...

### Background & Context

[MAX_NESTING_DEPTH remove contents issue](https://github.com/cure53/DOMPurify/issues/963)

Hello!

Unfortunately, the issue has not been resolved.

I am attaching a raw html file for you to test.
[sample.txt](https://github.com/user-attachments/files/15527551/sample.txt)

There are not many, but some users are experiencing an issue where their content is not being displayed.

I know you must be busy, but could you please check this?

* The actual user's text information has been changed to "TEST TEST," etc.

**Comment by cure53** [comment]
This cannot really be relating to the MAX_NESTING_DEPTH as the depth counter logic has been unimplemented completely. 

Can you maybe narrow down what gets removed, what your config looks like, etc? Currently we have no chance to debug this because it's not clear what the expected HTML would look like, what is missing etc.

**Comment by kakao-bishop-cho** [comment]
@cure53 

I'm sorry. 😢
Upon rechecking, it turns out we were using version 3.1.4.

During the rollup build process, it seemed like the issue wasn't resolved because the 3.1.4 version from the node_modules cache was continuously being used.

It appears to be working fine now.

Thank you!

**Comment by cure53** [comment]
Ah, cool :smile:
