### ISSUE TITLE
DOMpurify allows tampering by prototype pollution

### ISSUE THREAD

**Issue by Codename-404** [cure53/DOMPurify#994]
> This issue proposes a **security concern**

### Background & Context

Today we received an email from github that, **DOMpurify allows tampering by prototype pollution**. 
Can we expect a solution to this soon? 

#### Expected output

Not to have a security vulnerability

**Comment by luka-papez** [comment]
The issues has already been fixed, you just need to update to one of the versions containing the fix.

Please see the security advisory published here:

* https://github.com/cure53/DOMPurify/security/advisories/GHSA-mmhx-hmjr-r674

Note: I am not affiliated with the maintainers in any way, I was just passing by because I had a security scan fail on my pipeline.

Thank you maintainers for your hard work!
